version: '3'

services:
  bootstrap:
    image: enigmampc/secret-network-bootstrap-sw:latest
    container_name: bootstrap
    volumes:
      - /tmp/secretd:/root/.secretd
      - /tmp/secretcli:/root/.secretcli
    stdin_open: true
    tty: true
    environment:
      - http_proxy
      - https_proxy
    expose:
      - 26656
      - 26657

  node:
    image: enigmampc/secret-network-node-sw
    depends_on:
      - bootstrap
    volumes:
      - /tmp/secretd:/tmp/.secretd
      - /tmp/secretcli:/root/.secretcli
    stdin_open: true
    tty: true
    environment:
      - http_proxy
      - https_proxy
